### ISSUE TITLE
Missing the column on some accounts

### ISSUE THREAD

**Issue by Mte90** [tijn/gravatars#1]
In thunderbird I have 4 emails configured but the Gravatar column is showed only in two of them. The option is not available in the others...

**Comment by tijn** [comment]
That is rather curious and I'm clueless about it. Can you think of anything that these accounts without the option have in common?

**Comment by Mte90** [comment]
My fault, I didn't know that moving the column in an email is moved also in the others so now in the dropdown menu (to pick the columns) was moved up respect before that was the last.
Sorry for the disturb.

**Comment by tijn** [comment]
:relieved:
