### ISSUE TITLE
Add space between Gravatar and name

### ISSUE THREAD

**Issue by hurvajs** [tijn/gravatars#4]
Just a small improvement possible: Gravatar is very close to the name, so to make it better readable it would be good to add small space between gravatar and text. Probably to add one space (as a char) would be enough. This should be really siple to implement.

**Comment by tijn** [comment]
The plugin is not actively sending one string per mail `icon + ' ' + name_of_sender` to Thunderbird. That's not how it works. It only provides a very small component that corresponds to the API that Thunderbird expects. It is Thunderbird that asks my plugin for the icon, and the name of the sender.  (See https://github.com/tijn/gravatars/blob/master/chrome/content/gravatars.js#L88 and https://github.com/tijn/gravatars/blob/master/chrome/content/gravatars.js#L7-L30 .) It it Thunderbird who should add your extra space IMO. 

However, to solve your issue. You should read the source; It's probably *much* smaller than you expect. And then you can fork it and prepend the name with an extra space. Just insert the space `" "` in getCellText. I don't think I want to do this in this repository.
